### ISSUE TITLE
Ensuring controls are as simple as possible, or provide a simpler alternative

### ISSUE THREAD

**Issue by GodotWildJam** [GodotWildJam/gwj-accessibility-scripts#2]
More complex control schemes require higher degrees of both motor and cognitive skill, so avoid using buttons/keys just because they’re there. Having to remember complex combinations of controls, being required to reach every single button on a controller or even just having to press multiple buttons at the same time can all easily result in unnecessary exclusion.

Sometimes complex controls are required or desirable. If your game really does require complex controls, that is fine. It becomes an issue is when controls are more complex than they need to be.

But even when controls are necessarily complex by default, it can sometimes still be possible to provide options for simpler alternatives.

[More Information](http://gameaccessibilityguidelines.com/ensure-controls-are-as-simple-as-possible-or-provide-a-simpler-alternative/)

**Comment by Maaack** [comment]
Given the generalized contents of the repo, I'm not sure how this is actionable. Its origin is as a guideline for game developers, and I believe it is better suited for that. The same can be said of a number of the other items listed in [MOTOR.md](https://github.com/GodotWildJam/gwj-accessibility-scripts/blob/main/Motor/MOTOR.md) and [COGNITIVE.md](https://github.com/GodotWildJam/gwj-accessibility-scripts/blob/main/Cognitive/COGNITIVE.md).

Edit: Rest of comment moved to issues https://github.com/GodotWildJam/gwj-accessibility-scripts/issues/8 and https://github.com/GodotWildJam/gwj-accessibility-scripts/issues/9 .

**Comment by Maaack** [comment]
Since completing updating the Roadmap https://github.com/GodotWildJam/gwj-accessibility-scripts/issues/8, I think this issue is out of scope for the repo. I'll close the issue as no further action is intended at this time.
