### ISSUE TITLE
[Bug] the mappable hotkeys don't behave correctly when using keys mapped to UI actions

### ISSUE THREAD

**Issue by cyrilbos** [GodotWildJam/gwj-accessibility-scripts#4]
By default in Godot the InputMap defines multiple keys as ui_select and such. 

So for instance, if you have spacebar as the default of an action or try to map spacebar to an action, the current implementation does not work properly. Since it uses buttons that react to ui_select.

**Comment by GodotWildJam** [comment]
Fixed - see the linked PR
